elearning2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('welcome.urls')),
    path('lessons/', include('lessons.urls')),
]

lessons/urls.py
from django.urls import path

from . import views

app_name = 'lessons'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:lesson_id>/', views.detail, name = 'detail'),
    path('<int:lesson_id>/<int:video_id>/', views.loadvideo, name = 'loadvideo'),
    path('<int:lesson_id>/<int:video_id>/pass_video/', views.pass_video, name = 'pass_video'),
]

welcome/urls.py
from django.urls import path

from . import views

app_name = 'welcome'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('login/', views.login_user, name = 'login'),
    path('reg_user/', views.reg_user, name = 'reg_user'),
    path('reg_staff/', views.reg_staff, name = 'reg_staff'),
    path('logout/', views.user_logout, name = 'logout'),
    path('about_us/', views.about_us, name = 'about_us'),
    path('contact/', views.contact_us, name = 'contact'),
    path('teachorlearn/', views.teach_learn, name = 'teach_learn'),
    ]

lessons/models.py
import datetime
from django.db import models
from django.utils import timezone


class Lesson(models.Model):
    lesson_name = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('Data publikacji')
    
    def __str__(self):
        return self.lesson_name

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days = 1)

class Video(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete = models.CASCADE)
    video_name = models.CharField(max_length = 200)
    video_content = models.CharField(max_length = 400, blank = True, null = True)
    video_url = models.URLField(max_length = 200, blank = True, null = True)
    video_password = models.CharField(max_length = 100, blank = True, null = True)

    def __str__(self):
        return self.video_name


    

lessons/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse

from .models import Lesson, Video


def index(request):
    latest_lesson_list = Lesson.objects.order_by('-pub_date')[:5]
    template = loader.get_template('lessons/index.html')
    context = {
        'latest_lesson_list': latest_lesson_list,
    }
    return HttpResponse(template.render(context, request))

def detail(request, lesson_id):
    video_list = Video.objects.filter(lesson__pk = lesson_id)
    template2 = loader.get_template('lessons/detail.html')
    context = {
        'video_list': video_list,
    }
    return HttpResponse(template2.render(context, request))

def pass_video(request, video_id, lesson_id):
    video_lesson = Video.objects.filter(pk = video_id)
    video_list = Video.objects.filter(lesson__pk = lesson_id)
    template3 = loader.get_template('lessons/pass_video.html')
    context = {
        'video_lesson': video_lesson,
        'video_list': video_list,
    }
    return HttpResponse(template3.render(context, request))


def loadvideo(request, lesson_id, video_id):
    video_lesson = Video.objects.filter(pk = video_id)
    video_list = Video.objects.filter(lesson__pk = lesson_id)
    template3 = loader.get_template('lessons/loadvideo.html')
    context = {
        'video_lesson': video_lesson,
        'video_list': video_list,
    }
    return HttpResponse(template3.render(context, request))

lessons/templates/lessons/base.html
{% load static %}
<html>
<head> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'lessons/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'lessons/img/photo_bg.jpg' %}">
    <title>{% block title %} E-Learning Site {% endblock %} </title>
</head>
    <body> 
        <div class =  "navbar">
            <a href = "{% url 'welcome:index' %}"> Home </a> 
            <a href = "{% url 'welcome:about_us' %}"> About us </a> 
            <a href = "{% url 'welcome:contact' %}"> Contact us </a>
            <a href = "{% url 'lessons:index' %}"> Lessons </a>
            {% if user.is_authenticated %}
                    <a href = "{% url 'welcome:logout' %}"> Log out </a>
            {% else %}
                <a href = "{% url 'welcome:login' %}"> Log in </a> 
                <a href = "{% url 'welcome:teach_learn' %}"> Sign up </a>
            {% endif %}
        </div>    
        <div id = "content", name = "content">
            <div class = "row justify-content-center">
                <div class = "col-8">
                    <br><br>
                    <hr class = "mt-0 mb-4">
                    {% block content %}
​
                    {% endblock %}
                </div>
            </div>
        </div>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    </body>
</html>

lessons/templates/lessons/detail.html
{% extends "lessons/base.html" %}
{% load crispy_forms_tags %}

{% block title %} Topics {% endblock %}

{% block content %}
{% if user.is_authenticated %}

    {% if video_list %}
        <ul>
        <p><strong> Topics: </strong></p>
        <br>
        {% for video in video_list %}
            <li><strong><a href = "{{video.id}}"> {{ video.video_name }} </a></strong></li>
            <a> {{ video.video_content }} </a>     
            <br><br>

        {% endfor %}
        </ul>
    {% else %}
    <br><br>
        <p>No videos are available.</p>
    {% endif %}
{% else %}
        <div class = 'p'>
            <p><strong> Please log in or sign up.</strong></p>
        </div>
        <a href = "{% url 'welcome:login' %}"> Log in </a> 
        <br><br>
        <a href = "{% url 'welcome:index' %}"> Register </a>
{% endif %} 
{% endblock %}

lessons/templates/lessons/index.html
{% extends "lessons/base.html" %}

{% block title %} Lessons {% endblock %}

{% block content %}
{% if user.is_authenticated %}
    {% if latest_lesson_list %}
        <ul>
        <p><strong> Lessons: </strong></p>
        <br>
        {% for lesson in latest_lesson_list %}
            <li><a href="{{ lesson.id }}/{{video.id}}"> {{ lesson.lesson_name }} </a></li> 
            <br>
        {% endfor %}
        </ul>
    {% else %}
        <p>No lessons are available.</p>
    {% endif %}
{% else %}
    <br><br>
    <div class = 'p'>
        <p><strong> Please log in or sign up.</strong></p>
    </div>
    <a href = "{% url 'welcome:login' %}"><button class = 'button'> Log in </button></a> 
    <a href = "{% url 'welcome:index' %}"><button class = 'button'> Sign up </button></a>
{% endif %}
{% endblock %}

lessons/templates/lessons/loadvideo.html
{% extends "lessons/base.html" %}

{% block title %} VideoLesson {% endblock %}

{% block content %}
{% if user.is_authenticated %}
    {% if video_lesson %}
        <ul>
        {% for video in video_lesson %}
        <p><strong> {{video.video_name}} </strong></p>

        <body>
            <label for = 'password'> Password: </label>
            <input type = 'password' id = 'password'>
            <input type = 'hidden' id = 'video_password' value = "{{video.video_password}}" >
            <a><button class = 'button' type = 'button' onclick = 'compareText()'> Submit </button></a>          
            <br><br>

            <iframe style = "display:none" width = "520" height = "400" src = "{{video.video_url}}" title = "{{video.video_name}}" id = "v_lesson" allowfullscreen></iframe>

            <script type = "text/javascript">
                function compareText() {
                    var password = document.getElementById("password").value;
                    var truePassword = document.getElementById("video_password").value;

                    if (password == truePassword) {
                        document.getElementById("v_lesson").style.display = 'block';
                    } 
                    else {
                        alert("Wrong password");
                    }
                }
            </script>
        </body>    
                
        {% endfor %}
        </ul>
    {% else %}
        <p>No videos are available.</p>
        <br><br>
    {% endif %}
    {% if video_list %}
        <ul>
        <div class = 'sidenav'>
            <a><u> Other topics: </u></a>
            {% for video in video_list %}
                <a href = "/lessons/{{video.lesson_id}}/{{video.id}}"> {{ video.video_name }} </a>
            {% endfor %}
        </div>
        <br><br>
        </ul>
    {% endif %}
{% else %}
    <div class = 'p'>
        <p><strong> Please log in or sign up.</strong></p>
    </div>
    <a href = "{% url 'welcome:login' %}"> Log in </a> 
    <br><br>
    <a href = "{% url 'welcome:index' %}"> Register </a>
{% endif %}
{% endblock %}

lessons/templates/lessons/pass_video.html
{% extends "lessons/base.html" %}

{% block title %} Password {% endblock %}

{% block content %}
{% if user.is_authenticated %}
    {% if video_lesson %}
        <ul>
        {% for v in video_lesson %}
            <label for = 'password'> Password: </label>
            <input type = 'text' id = 'password'>
            <input type = 'hidden' id = 'video_password' value = "{{video.video_password}}" >

            <a><button class = 'button' onclick = 'compareText()'> Submit </button></a>   
            
            <script type="text/javascript">
                function compareText() {
                    var password = document.getElementById("password").value;
                    var truePassword = document.getElementById("video_password").value;

                    if (password == truePassword) {
                        alert("dupa")
                    } 
                    else {
                        alert("Wrong password");
                    }
                }
            </script>
        {% endfor %}
        </ul>
    {% else %}
        <p>No videos are available.</p>
        <br><br>
    {% endif %}
    {% if video_list %}
        <ul>
        <div class = 'sidenav'>
            <a><u> Other topics: </u></a>
            {% for video in video_list %}
                <a href = "/lessons/{{video.lesson_id}}/{{video.id}}"> {{ video.video_name }} </a>
            {% endfor %}
        </div>
        <br><br>
        </ul>
    {% endif %}
{% else %}
    <div class = 'p'>
        <p><strong> Please log in or sign up.</strong></p>
    </div>
    <a href = "{% url 'welcome:login' %}"> Log in </a> 
    <br><br>
    <a href = "{% url 'welcome:index' %}"> Register </a>
{% endif %}
{% endblock %}